.changeset/eighty-shoes-hunt.md
packages/mdxts/src/utils/get-git-metadata.ts

Fixes the `getGitMetadata` utility erroring when running MDXTS in a project that does not have git instantiated.
closes #81

fix git meta erroring when repo does not exist

---

.changeset/spotty-grapes-design.md
packages/mdxts/src/loader/index.ts
packages/mdxts/src/next/index.ts

This prepares MDXTS to work with [Turbopack](https://nextjs.org/docs/app/api-reference/next-config-js/turbo#webpack-loaders). However, it seems there are still some bugs detailed below.
It looks like `use client` directives aren't being handled correctly and result in the following import error:
Adding dynamic imports throw the following error in the console, but seems to compile and render fine on the client:
`Error: could not resolve "./docs/getting-started.mdx" into a module`

prepare for turbo

---

.changeset/witty-mirrors-confess.md
examples/blog/README.md
packages/create-mdxts/src/fetch-example.ts
packages/create-mdxts/src/index.ts
packages/create-mdxts/src/is-package-outdated.ts

This improves the CLI onboarding experience by prompting to install the [blog example](https://github.com/souporserious/mdxts/tree/main/examples/blog) if the CLI is not run in a project.
closes #87

improve cli onboarding

---

.changeset/warm-crews-begin.md
packages/mdxts/package.json
packages/mdxts/src/index.ts
packages/mdxts/src/loader/index.ts
pnpm-lock.yaml

Adds front matter type validation using the generic passed to `createSource`:
```ts
import { createSource } from 'mdxts'
export const allPosts = createSource<{
frontMatter: {
title: string
date: Date
summary: string
tags?: string[]
}
}>('posts/**/*.mdx', { baseDirectory: 'posts' })
```
```posts/markdown-guide.mdx
---
title: Hello World
date: 2021-01-01
---
This is a post.
```
Results in the following type error:
```
Error: Front matter data is incorrect or missing
[/posts/markdown-guide.mdx] Type '{}' does not satisfy the expected type 'frontMatter'.
Type '{}' is missing the following properties from type 'frontMatter': summary
```

front matter validation

---

packages/mdxts/src/components/CodeBlock.tsx
packages/mdxts/src/components/CodeInline.tsx
packages/mdxts/src/components/CodeToolbar.tsx
packages/mdxts/src/components/CodeView.tsx
packages/mdxts/src/components/Context.tsx
packages/mdxts/src/components/ExportedTypes.tsx
packages/mdxts/src/components/MDXContent.tsx
packages/mdxts/src/components/QuickInfo.tsx
packages/mdxts/src/components/highlighter.ts
packages/mdxts/src/index.ts
packages/mdxts/src/loader/index.ts
packages/mdxts/src/next/index.ts
packages/mdxts/src/utils/get-theme.ts
site/app/HeroExample.tsx

Simplifies the syntax highlighting theme propagation by simply setting an environment variable with the theme path and then loading the theme once through the `getTheme` utility.
fixes #70

simplify theme propagation

---

.changeset/hip-eagles-cheer.md
packages/mdxts/package.json
packages/mdxts/src/components/ContentRefresh.tsx
packages/mdxts/src/components/Context.tsx
packages/mdxts/src/components/CopyButton.tsx
packages/mdxts/src/components/PackageInstall.tsx
packages/mdxts/src/components/actions.ts
packages/mdxts/src/index.ts
packages/mdxts/src/loader/index.ts
packages/mdxts/src/next/index.ts
packages/mdxts/src/utils/get-all-data.test.ts
packages/mdxts/src/utils/get-all-data.ts
packages/mdxts/src/utils/get-entry-source-files.ts
packages/mdxts/src/utils/get-package-metadata.ts
pnpm-lock.yaml
site/data.ts

This normalizes the internal `getEntrySourceFiles` utility that is responsible for determining what TypeScript data sources are public based on `package.json` exports, index files, and top-level directories. It adds two new options to `createSource` used to remap `package.json` exports to their original source files:
```ts
import { createSource } from 'mdxts'
const allPackages = createSource(
'../packages/mdxts/src/**/*.{ts,tsx}',
{ sourceDirectory: 'src', outputDirectory: 'dist' }
)
```
Using the `mdxts` `package.json` exports as an example:
```json
"exports": {
".": {
"types": "./dist/src/index.d.ts",
"import": "./dist/src/index.js",
"require": "./dist/cjs/index.js"
},
"./components": {
"types": "./dist/src/components/index.d.ts",
"import": "./dist/src/components/index.js",
"require": …
```

normalize entry source files

---

.changeset/curly-mugs-count.md
packages/mdxts/src/components/CodeBlock/CodeBlock.examples.tsx
packages/mdxts/src/components/CodeBlock/CodeBlock.tsx
packages/mdxts/src/components/CodeBlock/Context.tsx
packages/mdxts/src/components/CodeBlock/LineNumbers.tsx
packages/mdxts/src/components/CodeBlock/get-diagnostics-or-throw.ts
packages/mdxts/src/components/CodeBlock/get-tokens.ts
packages/mdxts/src/components/MDXComponents.tsx
packages/mdxts/src/next/README.mdx
site/docs/01.getting-started.mdx
site/docs/04.examples/02.rendering.mdx

Enables type-checking code blocks to ensure they work correctly and don't produce type errors. To disable type errors, use `allowErrors`. Pair `allowErrors` with `showErrors` to visually display the inline error which is helpful for educational purposes.

enable type-checked code blocks

---

.changeset/blue-phones-tan.md
examples/blog/app/[slug]/page.tsx
packages/mdxts/src/index.ts
packages/mdxts/src/next/README.mdx
site/docs/01.getting-started.mdx
site/docs/02.routing.mdx

Refines `paths` returned from `createSource` and `mergeSources`. Based on the glob pattern provided, either a one-dimensional or two-dimensional array of paths will be returned:
```ts
import { createSource, mergeSources } from 'mdxts'
const allPosts = createSource('posts/*.mdx').paths() // string[]
const allDocs = createSource('docs/**/*.mdx').paths() // string[][]
const allPaths = mergeSources(allDocs, allPosts).paths() // string[] | string[][]
```
Likewise the `get` method will be narrowed to only accept a single pathname or an array of pathname segments:
```ts
allPosts.get('building-a-button-component-in-react')
allDocs.get(['examples', 'authoring'])
```
- The `paths` method now returns a one-dimensional array of paths for a single glob pattern and a two-dimensional array of paths for …

refine createSource paths

---

.changeset/witty-jars-drive.md
packages/mdxts/src/components/CodeBlock/CodeBlock.examples.tsx
packages/mdxts/src/components/CodeBlock/CodeBlock.tsx
packages/mdxts/src/components/CodeBlock/Context.tsx
packages/mdxts/src/components/CodeBlock/LineHighlights.tsx
packages/mdxts/src/components/CodeBlock/LineNumbers.tsx
packages/mdxts/src/components/CodeBlock/utils.ts

This adds `focusedLines` and `unfocusedLinesOpacity` props to the `CodeBlock` component to control focusing a set of lines and dimming the other lines. It uses an image mask to dim out the lines which can be controlled using `unfocusedLinesOpacity`:
````mdx
```tsx focusedLines="3-4"
const a = 1
const b = 2
const result = a + b
console.log(result) // 3
```
````
```tsx
<CodeBlock
value={`const a = 1;\nconst b = 2;\n\nconst add = a + b\nconst subtract = a - b`}
focusedLines="2, 4"
/>
```

add focusedLines prop to CodeBlock

---

.changeset/light-files-beg.md
packages/mdxts/src/components/GitProvider.examples.tsx
packages/mdxts/src/components/GitProvider.tsx
packages/mdxts/src/components/index.ts
site/components/Sidebar/Sidebar.tsx

Adds `GitProviderLink` and `GitProviderLogo` components to render links and graphics for the configured git provider.
```jsx
<GitProviderLink
style={{
width: 'var(--font-size-body-2)',
height: 'var(--font-size-body-2)',
fill: 'var(--color-foreground-interactive)',
}}
/>
```
```jsx
<a href="path/to/git-provider">
<GitProviderLogo />
</a>
```

add git provider components

---

.changeset/long-badgers-grab.md
packages/mdxts/src/utils/get-entry-source-files.ts

I use deeply nested package exports and was running into an issue since that edge case wasn't included yet.
I added some code to handle cases like this, where we have deeply nested configuration per export type.
```ts
"exports": {
"./tailwind": {
"import": {
"types": "./dist/es/tailwind.d.mts",
"default": "./dist/es/tailwind.mjs"
},
"require": {
"types": "./dist/cjs/tailwind.d.ts",
"default": "./dist/cjs/tailwind.js"
}
}

fix: nested package exports

---

.changeset/cold-singers-shake.md
packages/create-mdxts/src/index.ts
packages/create-mdxts/src/utils.ts
packages/mdxts/src/components/CodeBlock/get-tokens.ts
packages/mdxts/src/components/CodeBlock/parse-source-text-metadata.ts
packages/mdxts/src/index.ts
packages/mdxts/src/loader/index.ts
packages/mdxts/src/mdx-plugins/remark/transform-relative-links.ts
packages/mdxts/src/utils/file-path-to-pathname.ts
packages/mdxts/src/utils/get-all-data.ts
packages/mdxts/src/utils/get-shared-directory-path.ts
packages/mdxts/src/utils/get-source-path.ts

Per the recommendation in https://github.com/souporserious/mdxts/issues/108#issuecomment-2116958111 this normalizes path separators to `posix.path` since this is supported in Windows according to [this StackOverflow answer](https://stackoverflow.com/a/63251716/1461204).

use posix separator

---

.changeset/dirty-moons-heal.md
packages/mdxts/src/components/CodeBlock/CodeBlock.tsx
packages/mdxts/src/components/CodeBlock/parse-source-text-metadata.ts
packages/mdxts/src/components/GitProvider.examples.tsx
site/app/examples/[...example]/page.tsx

Removes the `fixImports` prop from `CodeBlock`. This prop fixed imports specifically for situations like examples that are located in a different project and used relative imports. However, this can be extremely slow to calculate in large codebases due to the constant AST traversals from ts-morph. Examples should [use the library import path](https://github.com/souporserious/mdxts/commit/b6c22466ced5e471ecd7411b796f0e305559eb72) instead of relative paths by configuring the `module` field in `tsconfig.json`. More info [here](https://x.com/remcohaszing/status/1794338155963064548).

remove CodeBlock fixImports prop

---

.changeset/gentle-games-play.md
packages/mdxts/src/components/CodeBlock/CodeBlock.tsx
packages/mdxts/src/components/CodeBlock/CopyButton.tsx
packages/mdxts/src/components/CodeBlock/contexts.tsx
packages/mdxts/src/components/CodeBlock/index.ts
packages/mdxts/src/components/index.ts

This exposes the previously internal `CopyButton` component for use within custom `CodeBlock` components.

add CopyButton component

---

.changeset/yellow-hounds-tell.md
packages/mdxts/src/utils/file-path-to-pathname.test.ts
packages/mdxts/src/utils/file-path-to-pathname.ts

* Updated the `filePathToPathname` to ensure
* There is a trailing slash in the `baseDirectory` before we run the `.split()`
* There is a leading slash in the `baseFilePath` before we start the generation of `parsedFilePath`
* Added the missing tests
Fixes #148

fix: Pathname generation with same name

---

.changeset/young-beers-lick.md
apps/site/app/(site)/collections/docs/recipes.mdx
apps/site/app/(site)/collections/intro.mdx
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/components/DocumentSource.tsx
apps/site/components/Sidebar/Sidebar.tsx
examples/blog/app/[slug]/page.tsx
examples/blog/app/page.tsx
examples/blog/collections.ts
examples/design-system/app/components/[...slug]/page.tsx
packages/renoun/src/collections/index.tsx
packages/renoun/src/utils/get-exported-declaration.ts

Removes `getDefaultExport` and `getNamedExport` from collection export sources in favor of a new `getExport` method. This method works exactly the same as the previous `getNamedExport` method with the addition of accepting `default` as an export. This simplifies the API and reduces the number of methods needed to query an export source.
Update any usage of `getDefaultExport` and `getNamedExport` to use the new `getExport` method:
- `getDefaultExport()` -> `getExport('default')`
- `getNamedExport('metadata')` -> `getExport('metadata')`

add getExport method

---

.changeset/happy-toes-wash.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

This update resolves several issues with API references, particularly recursion bugs in the internal `resolveType` utility. The key changes involve an updated algorithm for computing component types, which affects the following case:
- Named functions with a capitalized first letter and a single non-object argument are now interpreted as components when they should be functions. This is an unintended behavior change and will be corrected in an upcoming update.
Type references are now split into two maps that serve the following use cases:
- **Prevent Infinite Recursion**: A map of type references is maintained during type iteration of the root type to prevent infinite recursion.
- **Optimized Type Handling for Exported Declarations**:
- Adds an explicit map for tracking exported …

fix infinite type recursion

---

.changeset/odd-camels-report.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

Adds support to `<ExportSource>.getType()` for capturing API references that use index types e.g.
```ts
export interface FileExports {
[key: string]: unknown
}
```

add support for index types

---

.changeset/famous-hairs-vanish.md
apps/site/app/(site)/collections/page.tsx
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/app/(site)/docs/[...slug]/page.tsx
apps/site/app/(site)/guides/[...slug]/page.tsx
apps/site/collections.ts
packages/renoun/src/collections/docs/index.mdx
packages/renoun/src/collections/get-collection-call-expressions.ts
packages/renoun/src/collections/index.test.ts
packages/renoun/src/collections/index.tsx
packages/renoun/src/utils/get-exported-declaration.test.ts
packages/renoun/src/utils/get-exported-declaration.ts

Introduces a concept of "composite collections". This allows overloading the `collection` utility to treat a set of collections as a single collection:
```tsx
const CollectionsCollection = collection({
filePattern: 'src/collections/index.tsx',
baseDirectory: 'collections',
})
const ComponentsCollection = collection({
filePattern: 'src/components/**/*.{ts,tsx}',
baseDirectory: 'components',
})
const AllCollections = collection(CollectionsCollection, ComponentsCollection)
```
When getting a source from a composite collection, the `<FileSystemSource>.getSiblings` method will account for all collections in the composite collection:
```tsx
const source = AllCollections.getSource('collections/index')!
const [previousSource, nextSource] = await source.getSiblings()
```
A new …

composite collections

---

.changeset/shaggy-numbers-matter.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

Adds support to `<ExportSource>.getType()` for capturing API references that use generic parameters e.g.
```ts
export function getValue<T>(value: T): T {
return value
}
```

add support for generic parameters

---

.changeset/new-shoes-swim.md
packages/renoun/src/project/index.ts
packages/renoun/src/project/server.ts
packages/renoun/src/utils/resolve-type-at-location.ts
packages/renoun/src/utils/resolve-type.ts

Adds a cache to the `<ExportSource>.getType` method to prevent unnecessary processing of types since this is an expensive operation. Types will now only be resolved the first time they are requested and then cached for subsequent requests unless one of the file dependencies has changed. This dramatically improves subsequent updates during local development.
In the future, other areas should benefit from a similar caching strategy for syntax highlighting and diagnostics.

cache export source getType

---

.changeset/smart-beds-learn.md
apps/site/app/(site)/collections/[...slug]/page.tsx
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/app/(site)/docs/[...slug]/page.tsx
apps/site/app/(site)/guides/[...slug]/page.tsx
apps/site/collections.ts
apps/site/components/SiblingLink.tsx
apps/site/components/Sidebar/Sidebar.tsx
apps/site/docs/02.getting-started.mdx
apps/site/guides/04.zod.mdx
apps/site/guides/05.valibot.mdx
examples/blog/collections.ts
examples/design-system/app/components/[...slug]/page.tsx
examples/design-system/collections.ts
examples/design-system/package.json
packages/renoun/src/README.mdx
packages/renoun/src/collections/docs/index.mdx
packages/renoun/src/collections/index.test.ts
packages/renoun/src/collections/index.tsx
packages/renoun/src/collections/write-collection-imports.ts
packages/renoun/src/components/APIReference.tsx
packages/renoun/src/utils/file-path-to-pathname.test.ts
packages/renoun/src/utils/file-path-to-pathname.ts
packages/renoun/src/utils/get-directory-source-file.test.ts
packages/renoun/src/utils/get-directory-source-file.ts
packages/renoun/src/utils/get-source-files-path-map.ts

Simplifies how `baseDirectory` works for `Collection`. This was from a legacy implementation that was not well thought out and caused confusion and subtle bugs. This change makes it more explicit and easier to understand.
The `baseDirectory` option for `Collection` is now required to be separate from `filePattern`:
```diff
import { Collection } from 'renoun/collections'
const components = new Collection({
--  filePattern: 'src/components/**/*.ts',
++  filePattern: '**/*.ts',
--  baseDirectory: 'components',
++  baseDirectory: 'src/components',
})
```

simplify collection base directory

---

apps/site/guides/05.valibot.mdx

The `https://github.com/valibot/valibot` repo does not exist. Also, I think it's better to point to the actual valibot documentation located at `https://valibot.dev`.

update valibot documentation reference

---

.changeset/modern-tools-wink.md
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx

Adds an `EntryGroup` utility to `renoun/file-system` that provides an interface for querying and navigating a group of entries:
```ts
import { Directory, EntryGroup } from 'renoun/file-system'
interface FrontMatter {
title: string
description?: string
date: string
tags?: string[]
}
interface MDXType {
frontmatter: FrontMatter
}
const posts = new Directory<{ mdx: MDXType }>({ path: 'posts' })
const docs = new Directory<{ mdx: MDXType }>({ path: 'docs' })
const group = new EntryGroup({ entries: [posts, docs] })
const entries = await group.getEntries()
```
This also adds `getHasEntry` and `getHasFile` methods to `Directory` which can be used to check if an entry or file exists in an `EntryGroup`:
```ts
type MDXTypes = { metadata: { title: string } }
type TSXTypes = { title: string }
const …
```

add EntryGroup utility

---

.changeset/hip-bats-worry.md
apps/site/app/(home)/QuickSteps.tsx
examples/blog/collections.ts
examples/design-system/collections.ts
packages/renoun/README.md
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx

Moves the `Directory` `getImport` option to `<Directory>.withModule`. This provides stronger types for inferring the `getRuntimeValue` method:
```ts
export const posts = new Directory<{ mdx: PostType }>({
path: 'posts',
schema: { mdx: { frontmatter: frontmatterSchema.parse } },
})
.withModule((path) => import(`./posts/${path}`))
const file = posts.getFileOrThrow('hello-world', 'mdx')
const export = file.getExport('default').getRuntimeValue() // Now available only when withModule is provided
```
The previous implementation using the `getModule` option could not be inferred since the first generic slot is used for extension types.

refactor getImport to withImport

---

.changeset/khaki-donkeys-sit.md
examples/blog/collections.ts
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx

Moves the `Directory` `schema` option to `<Directory>.withSchema`. This aligns with the recent refactor of the `getImport` option to `<Directory>.withModule`.
Update the `schema` option to `withSchema`:
```ts
export const posts = new Directory<{ mdx: PostType }>({ path: 'posts' })
.withSchema('mdx', { frontmatter: frontmatterSchema.parse })
```

refactor schema to withSchema

---

.changeset/lazy-camels-appear.md
packages/renoun/src/file-system/FileSystem.ts
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx

Moves the `Directory` `basePath` option to `<Directory>.withBasePath`. This aligns with the recent refactor of other `Directory` options.
Update the `basePath` option to `withBasePath`:
```ts
export const posts = new Directory<{ mdx: PostType }>({
path: 'posts',
})
.withBasePath('blog')
```

refactor basePath to withBasePath

---

.changeset/fair-candles-grin.md
.changeset/few-swans-call.md
apps/site/app/(home)/QuickSteps.tsx
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/app/(site)/docs/[...slug]/page.tsx
apps/site/app/(site)/guides/[...slug]/page.tsx
apps/site/app/(site)/guides/page.tsx
apps/site/app/(site)/utilities/file-system/page.tsx
apps/site/components/DocumentEntry.tsx
apps/site/components/SiblingLink.tsx
apps/site/components/Sidebar/TreeNavigation.tsx
apps/site/docs/02.getting-started.mdx
apps/site/guides/02.next.mdx
apps/site/guides/AllGuides.tsx
examples/blog/app/[slug]/page.tsx
examples/blog/app/page.tsx
examples/blog/collections.ts
examples/design-system/app/components/[slug]/page.tsx
packages/renoun/README.md
packages/renoun/src/file-system/README.mdx
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx
packages/renoun/src/project/get-project.ts

Removes all `*OrThrow` methods from `Directory` and `EntryGroup` which aligns the API better with how `node:fs` works. The throw methods were originally borrowed from `ts-morph`, however this wasn't fully consistent with the other methods and made maintenance more cumbersome.
This additionally exports two new custom errors, `FileNotFoundError` and `FileExportNotFoundError` to help with catching and handling missing files and exports.
`Directory` and `EntryGroup` no longer have `*OrThrow` methods, use the respective methods instead. To get the same functionality as before, you can catch the error and handle it accordingly:
```ts
import { Directory } from 'renoun/file-system'
const posts = new Directory({ path: 'posts' })
posts.getFile('hello-world', 'mdx').catch((error) => {
if (error …
```

remove file system throw methods

---

.changeset/wise-eggs-boil.md
apps/site/guides/02.next.mdx
apps/site/next.config.mjs
packages/renoun/src/cli/index.ts
packages/renoun/src/file-system/Refresh.tsx
packages/renoun/src/file-system/index.tsx
packages/renoun/src/project/rpc/client.ts
packages/renoun/src/project/rpc/server.ts
packages/renoun/src/project/server.ts

Fixes running multiple renoun WebSocket servers by setting the port to `0` by default. This allows the OS to assign an available port.
This also adds a new `startServer` function that will only ever start the WebSocket server once per process. This is useful in frameworks like Next.js where the configuration is not shared across multiple instances.
```ts
import { startServer } from 'renoun/server'
await startServer()
```
closes #178

fix running multiple servers

---

.changeset/fast-mayflies-clap.md
packages/renoun/src/components/CodeBlock/CodeBlock.tsx

This fixes the `CodeBlock` fallback so it uses the exact same styles to prevent layout shift. This is only run during development while communicating with the WebSocket to calculate syntax highlighting and quick info, but makes for a nicer experience overall.
https://github.com/user-attachments/assets/5e936a89-bd65-4962-b384-883e6bd465e6

fix CodeBlock fallback layout shift

---

.changeset/unlucky-laws-jump.md
packages/create-renoun/CHANGELOG.md
packages/create-renoun/LICENSE.md
packages/create-renoun/README.md
packages/create-renoun/package.json
packages/create-renoun/src/bin/index.mts
packages/create-renoun/src/fetch-example.ts
packages/create-renoun/src/get-package-version.ts
packages/create-renoun/src/is-package-outdated.ts
packages/create-renoun/src/pick-example.ts
packages/create-renoun/src/utils.ts
packages/create-renoun/tsconfig.json
pnpm-lock.yaml

Adds the initial release of the `create-renoun` CLI based on the previous [`create-mdxts` CLI](https://github.com/souporserious/renoun/tree/mdxts%402.0.1/packages/create-mdxts). This package is currently a scaffolding tool for renoun examples. It provides a simple way to clone an example with the necessary configuration and dependencies.

create renoun cli

---

.changeset/slimy-chairs-travel.md
apps/site/app/schema.json/route.ts
apps/site/docs/03.configuration.mdx
examples/design-system/renoun.json
packages/renoun/src/utils/create-highlighter.ts
packages/renoun/src/utils/get-theme.ts
packages/renoun/src/utils/get-tokens.ts

Adds the ability to override specific theme values. You can now provide a tuple when configuring themes that specifies the specific theme values to override:
```json
{
"theme": {
"light": "vitesse-light",
"dark": [
"vitesse-dark",
{
"colors": {
"editor.background": "#000000",
"panel.border": "#666666"
}
}
]
}
}
```
This accepts a subset of a VS Code theme to override, specifically the `colors`, `tokenColors`, and `semanticTokenColors` properties.

theme overrides

---

.changeset/vast-laws-relax.md
packages/renoun/src/file-system/Repository.ts

Adds [Pierre](https://pierre.co/) as a git provider option that can be configured in the `renoun.json` file:
```json
{
"git": {
"source": "https://pierre.co/souporserious/renoun"
}
}
```

add pierre git provider

---

.changeset/legal-terms-drop.md
apps/site/components/DocumentEntry.tsx
apps/site/components/SiblingLink.tsx
packages/renoun/package.json
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx
packages/renoun/src/utils/is-javascript-like-extension.ts
packages/renoun/vitest.config.ts
pnpm-lock.yaml

This adds `MDXFile`, `MDXFileExport`, and `isMDXFile` classes and utilities to better differentiate between specific MDX and JavaScript file methods. This also helps with performance since we should never attempt to analyze an MDX file using the TypeScript compiler and allows for future MDX-specific methods to be added.
In some cases there may be breaking changes if you were loading mdx files and targeting `JavaScriptFile` related classes or types. These should be transitioned to the new `MDXFile`, `MDXFileExport`, and `isMDXFile` respectively.

add MDXFile class

---

.changeset/fresh-cows-help.md
examples/blog/app/[slug]/page.tsx
packages/renoun/src/file-system/index.tsx

With the latest changes in renoun 8.7.0 and providing the `MDXFile` class, we had some problems in the CI to build the blog example app.
After analyzing the code, it seems that the rootcause is/was the missing parse logic inside the `MDXFile` class.
This PR adds the missing methods.
Maybe we could use a generic parse method to have the same behaviour for `JavaScriptFile` and `MDXFile`, but for now, I just copied the code and updated the error message to show the correct class name.

parse frontmatter in mdx files

---

.changeset/open-insects-join.md
packages/renoun/src/components/CodeBlock/QuickInfo.tsx
packages/renoun/src/components/CodeBlock/Toolbar.tsx
packages/renoun/src/utils/get-theme.ts

This improves the fallback theme colors used throughout components to better match the theme author's intent. It also improves the internal types for `getThemeColors` to ensure that internal components only use variables that have defined fallbacks.

improve theme fallback colors

---

.changeset/loud-pans-poke.md
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/collections/renoun.ts
apps/site/collections/site.ts
apps/site/components/TableOfContents.tsx
apps/site/mdx.d.ts
packages/mdx/package.json
packages/mdx/src/remark/add-headings.test.ts
packages/mdx/src/remark/add-headings.ts
packages/renoun/src/file-system/index.test.ts
pnpm-lock.yaml

Updates exported `headings` variable from the `addHeadings` remark plugin to include a new `children` property to allow rendering the JSX children of the heading element.
For example, headings with inline code or links:
```mdx
```
Roughly yields:
```mdx
export const headings = [
{
level: 1,
id: 'heading-with-code',
text: 'Heading with code',
children: (
<>
Heading with <code>code</code>
</>
),
},
]
```
The `depth` property of the heading metadata object was renamed to `level` to better reflect HTML nomenclature.

jsx headings

---

.changeset/hungry-facts-appear.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

Fixes `JavaScriptFile#getType` union member references that point to external unions from resolving to their intrinsic type. References are now preserved correctly for all union members even when the member itself a union. An example of where this was previously broken could be seen in the `CodeBlock` `language` prop that used an external `Languages` type:
```ts
export Languages = 'jsx' | 'tsx'
```
```tsx
import type { Languages } from './types'
export interface CodeBlockProps {
language?: Languages | 'mdx'
}
export function CodeBlock({ language }: CodeBlockProps) {
return <pre />
}
```
This would previously resolve to flat union members `jsx | tsx | mdx` instead of `Languages | 'mdx'`. This is now fixed and the type will resolve to `Languages | 'mdx'` as expected.

fix resolved union member references

---

.changeset/stupid-things-cheat.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

Filters `undefined` union member types from optional properties in `JavaScriptFile#getType`. When using `strictNullChecks`, optional properties would previously add an `undefined` member to the union type. However, this is not necessary for the generated metadata and adds noise to the type text.

filter undefined union member types

---

packages/renoun/src/components/APIReference.tsx
packages/renoun/src/utils/index.ts
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

This cleans up the internal `resolveType` utility used in `JavaScriptFile#getType` to be closer to the TypeScript AST nomenclature.

clean up resolved types

---

.changeset/good-clocks-press.md
.changeset/some-squids-kick.md
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/components/MDX.tsx
apps/site/guides/01.mdx.mdx
packages/renoun/README.md
packages/renoun/src/components/APIReference.tsx
packages/renoun/src/components/CodeBlock/QuickInfo.tsx
packages/renoun/src/components/MDX.examples.tsx
packages/renoun/src/components/MDX.mdx
packages/renoun/src/components/MDX.tsx
packages/renoun/src/components/MDXRenderer.examples.tsx
packages/renoun/src/components/MDXRenderer.mdx
packages/renoun/src/components/index.ts

Renames the `MDXRenderer` component to `MDX`. This is to better align with the new `Markdown` component.
Rename any `MDXRenderer` component references imported from `renoun/components` to `MDX`.

rename MDXRenderer -> MDX

---

.changeset/modern-cats-sneeze.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

Adds analysis for mapped types to `JavaScriptFileExport#getType` by introducing a new `Mapped` kind. This will now capture mapped types instead of always expanding them fully which would result in large and repetitive types.

support mapped types

---

.changeset/fifty-kids-stare.md
apps/site/app/(site)/components/[...slug]/page.tsx
apps/site/app/(site)/components/page.tsx
apps/site/app/(site)/docs/[...slug]/page.tsx
apps/site/app/(site)/guides/[...slug]/page.tsx
apps/site/collections/renoun.ts
apps/site/collections/site.ts
apps/site/components/SiblingLink.tsx
apps/site/components/Sidebar/TreeNavigation.tsx
apps/site/docs/02.getting-started.mdx
apps/site/guides/02.next.mdx
apps/site/guides/AllGuides.tsx
examples/blog/app/page.tsx
examples/design-system/app/components/[slug]/page.tsx
examples/design-system/app/components/page.tsx
examples/design-system/collections.ts
packages/renoun/README.md
packages/renoun/src/file-system/FileSystem.ts
packages/renoun/src/file-system/README.mdx
packages/renoun/src/file-system/index.test.ts
packages/renoun/src/file-system/index.tsx

Renames the `Directory` and `File` path methods to better align with their intended use. The `basePath` constructor option has also been renamed to `baseRoutePath` to match the new naming convention. Additionally, the `baseRoutePath` option now defaults to the root directory's slug since this is the most common use case.
Rename any call sites that use the following `Directory` and `File` methods:
- `getPath` to `getRoutePath`
- `getPathSegments` to `getRouteSegments`
In most cases, you can remove the `baseRoutePath` option from your code if you were using it to set the base path for a directory. It now defaults to the root directory's slug:
```diff
import { Directory } from 'renoun/file-system';
const directory = new Directory({
path: 'components',
--  basePath: 'components'
});
const …
```

rename path methods

---

.changeset/metal-olives-fold.md
packages/renoun/src/file-system/GitProviderFileSystem.ts
packages/renoun/src/file-system/index.tsx
packages/renoun/src/project/rpc/server.ts
packages/renoun/src/utils/Semaphore.ts

Adds a `GitProviderFileSystem` utility that extends `MemoryFileSystem` by fetching a git provider repository using the respective provider's API to allow enumeration of the repository's contents.

add GitProviderFileSystem utility

---

.changeset/add-headings-override.md
apps/site/guides/01.mdx.mdx
packages/mdx/src/remark/add-headings.test.ts
packages/mdx/src/remark/add-headings.ts

Allows MDX files to override the exported `headings` variable by exporting a `getHeadings` function. Note, this is disabled by default, please read more below.
```hello-world.mdx
export function getHeadings(headings) {
return [
...headings,
{ id: 'extra', level: 2, text: 'Extra', children: 'Extra' },
]
}
```
This will now include the extra headings when importing them from the file:
```tsx allowErrors
import Content, { headings } from 'hello-world.mdx'
```
This feature is disabled by default for security purposes, please import and configure this plugin to enable:
```tsx
import { remarkAddHeadings } from '@renoun/mdx/add-headings'
import { evaluate } from '@mdx-js/mdx'
const result = await evaluate('# Hello World', {
remarkPlugins: [[addHeadings, { allowGetHeadings: true }]],
})
``` …

allow overriding headings

---

.changeset/nine-steaks-feel.md
packages/renoun/src/utils/resolve-type.test.ts
packages/renoun/src/utils/resolve-type.ts

Fixes `JavaScriptFileExport#getType` causing maximum call stack exceeded errors when resolving recursive array types (e.g. `type A = A[]`). We now use the internal compiler id to track references instead of the `Type` since the TypeScript compiler will wrap a fresh type for arguments which breaks the recursion guard.

fix resolved recursive array types

---

.changeset/happy-hounds-stand.md
apps/site/app/(site)/sponsors/SponsorTiers.tsx
apps/site/app/(site)/sponsors/page.tsx
apps/site/app/(site)/sponsors/sponsors.mdx
packages/renoun/package.json
packages/renoun/src/components/Sponsors.mdx
packages/renoun/src/components/Sponsors.tsx
packages/renoun/src/components/index.ts
pnpm-lock.yaml

Adds a `Sponsors` component for rendering GitHub sponsors related to a specific user account. Note, this requires providing a `GITHUB_SPONSORS_TOKEN` with a `read:user` scope. The component will return formatted data for each sponsorship tier related to the user token:
```tsx
import { Sponsors } from "renoun/components";
export function SponsorTiers() {
return (
<Sponsors
tiers={[
{ amount: 1000, title: "Gold", icon: "🏅" },
{ amount: 500, title: "Silver", icon: "🥈" },
{ amount: 100, title: "Bronze", icon: "🥉" },
]}
>
{(tiers) => (
<section>
{tiers.map((tier) => (
<section key={tier.title}>
<h3>
{tier.icon} {tier.title}
</h3>
{tier.sponsors.length ? (
<ul>
{tier.sponsors.map((sponsor) => (
<li key={sponsor.username}>
<a href={`https://github.com/${sponsor.username}`}>
</a>
</li>
))}
</ul> …
```

add Sponsors component

---

.changeset/ready-mails-clap.md
packages/renoun/src/cli/index.ts

Fixes error when locating the vite bin file when using the renoun cli.
closes #300

fix missing vite bin file

---

.changeset/gentle-crabs-throw.md
packages/renoun/src/components/Script.mdx
packages/renoun/src/components/Script.tsx
packages/renoun/src/components/index.ts

Adds a `Script` component that lets you author a client-side script using a normal source file that is then injected into HTML either inline, deferred, or as a hoisted data URL. This is useful for small scripts like analytics snippets, theme preferences, feature flags, or bootstrapping navigation active states.
```tsx path="app/page.tsx"
import { Script } from 'renoun'
export default function RootLayout({
children,
}: {
children: React.ReactNode
}) {
return (
<html>
<head>
<Script>{import('./table-of-contents-script.ts')}</Script>
</head>
<body>{children}</body>
</html>
)
}
```

add Script component
